// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    public partial class BotCommand
    {
        public BotCommand()
        {
            BotCommandAliases = new HashSet<BotCommandAlias>();
            BotCommandParameters = new HashSet<BotCommandParameter>();
            CommandStats = new HashSet<CommandStat>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string CommandName { get; set; }
        [Required]
        public string Summary { get; set; }
        [Required]
        [StringLength(200)]
        public string Example { get; set; }
        [Required]
        [StringLength(50)]
        public string Module { get; set; }
        [Required]
        public bool? Display { get; set; }

        [InverseProperty(nameof(BotCommandAlias.Command))]
        public virtual ICollection<BotCommandAlias> BotCommandAliases { get; set; }
        [InverseProperty(nameof(BotCommandParameter.Command))]
        public virtual ICollection<BotCommandParameter> BotCommandParameters { get; set; }
        [InverseProperty(nameof(CommandStat.Command))]
        public virtual ICollection<CommandStat> CommandStats { get; set; }
    }
}