// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    [Table("BotCommandParameter")]
    public partial class BotCommandParameter
    {
        [Key]
        public int Id { get; set; }
        public int CommandId { get; set; }
        [Required]
        [StringLength(50)]
        public string ParamName { get; set; }

        [ForeignKey(nameof(CommandId))]
        [InverseProperty(nameof(BotCommand.BotCommandParameters))]
        public virtual BotCommand Command { get; set; }
    }
}