// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dubot.Data.Models
{
    public partial class CommandsPerHourResult
    {
        public DateTime? Date { get; set; }
        public int? Hour { get; set; }
        public int? Count { get; set; }
    }
}
