// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dubot.Data.Models
{
    public partial class CommandsPerDayPerPersonResult
    {
        public int? Count { get; set; }
        public DateTime? Day { get; set; }
        public string UserName { get; set; }
    }
}
