// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    public partial class GuildSetting
    {
        [Key]
        public int Id { get; set; }
        public long GuildId { get; set; }
        [Required]
        [StringLength(50)]
        public string GuildName { get; set; }
        public int SettingId { get; set; }
        [Required]
        [StringLength(512)]
        public string Value1 { get; set; }
        [StringLength(512)]
        public string Value2 { get; set; }
        public long CreatedId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [ForeignKey(nameof(GuildId))]
        [InverseProperty("GuildSettings")]
        public virtual Guild Guild { get; set; }
        [ForeignKey(nameof(SettingId))]
        [InverseProperty("GuildSettings")]
        public virtual Setting Setting { get; set; }
    }
}