// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    public partial class Guild
    {
        public Guild()
        {
            GuildMembers = new HashSet<GuildMember>();
            GuildSettings = new HashSet<GuildSetting>();
        }

        [Key]
        public long GuildId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Owner { get; set; }
        [StringLength(3)]
        public string CmdPrefix { get; set; }

        [InverseProperty(nameof(GuildMember.Guild))]
        public virtual ICollection<GuildMember> GuildMembers { get; set; }
        [InverseProperty(nameof(GuildSetting.Guild))]
        public virtual ICollection<GuildSetting> GuildSettings { get; set; }
    }
}