// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    public partial class ItemCategory
    {
        public ItemCategory()
        {
            InverseParentCategory = new HashSet<ItemCategory>();
            Items = new HashSet<Item>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string CategoryName { get; set; }
        public int Sequence { get; set; }
        public int? ParentCategoryId { get; set; }
        [StringLength(50)]
        public string ParentCategoryName { get; set; }

        [ForeignKey(nameof(ParentCategoryId))]
        [InverseProperty(nameof(ItemCategory.InverseParentCategory))]
        public virtual ItemCategory ParentCategory { get; set; }
        [InverseProperty(nameof(ItemCategory.ParentCategory))]
        public virtual ICollection<ItemCategory> InverseParentCategory { get; set; }
        [InverseProperty(nameof(Item.Category))]
        public virtual ICollection<Item> Items { get; set; }
    }
}