// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    public partial class Planet
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string PlanetName { get; set; }
        public int? ParentPlanetId { get; set; }
        [Column(TypeName = "decimal(3, 2)")]
        public decimal? Gravity { get; set; }
        public int? Atmosphere { get; set; }
    }
}