// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    public partial class Setting
    {
        public Setting()
        {
            GuildSettings = new HashSet<GuildSetting>();
        }

        [Key]
        public int SettingId { get; set; }
        [Required]
        [StringLength(50)]
        public string Description { get; set; }

        [InverseProperty(nameof(GuildSetting.Setting))]
        public virtual ICollection<GuildSetting> GuildSettings { get; set; }
    }
}