// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Dubot.Data.Models
{
    [Table("TimeZone")]
    public partial class TimeZone
    {
        [Key]
        public int Id { get; set; }
        public long UserId { get; set; }
        [StringLength(50)]
        public string TimeZoneId { get; set; }
    }
}